source 'https://rubygems.org'

gem "pact_broker", git: "https://github.com/pact-foundation/pact_broker.git", ref: "0cf6129d336bb5e1cd6973b604c3128d389b33ed"
gem "pg", "~>1.0"
gem "puma", "~> 5.3"
gem "mysql2", "~>0.3"
gem "sqlite3", "~>1.3"
gem "rake", "~> 13.0"

# Need to manually add Webrick because we deleted it from the underlying Docker image
# because of a vulnerability, and Webmachine requires it in the adapters.rb file.
gem "webrick", "~> 1.6"
