source 'https://rubygems.org'

gem "pact_broker"
gem "pg", "~>1.5"
gem "puma", "~> 6.0"
gem "mysql2", "~>0.3"
gem "sqlite3", "~>2.0", force_ruby_platform: true
gem "rake", "~> 13.0"
gem "padrino-core", ">= 0.16.0.pre3"
gem "sinatra", "~> 4.0"
gem "pact-support"