version: "3"

services:
  postgres:
    image: postgres:12
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ${PWD}/docker/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${PWD}/docker/pg-dump.sql:/tmp/pg-dump.sql

  pact-broker:
    image: "pactfoundation/pact-broker:2.110.0-pactbroker2.107.1"
    ports:
      - "9393:9393"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: "INFO"
      PACT_BROKER_SQL_LOG_LEVEL: "DEBUG"
      PACT_BROKER_DATABASE_CLEAN_ENABLED: "true"
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_DATABASE_CLEAN_CRON_SCHEDULE: "* * * * *"
      PACT_BROKER_DATABASE_CLEAN_DELETION_LIMIT: "500"
      PACT_BROKER_SQL_LOG_WARN_DURATION: "60"
      # Keep all prod versions, AND the latest version for every pacticipant/tag, and all versions less than 30 days old
      PACT_BROKER_DATABASE_CLEAN_KEEP_VERSION_SELECTORS: '[{"latest": true, "tag": true}, {"max_age": 30}]'
