FROM ruby:4.0.6-alpine3.24@sha256:6ec7aeb4f3f0b67a21fb73a83fc20a4055696e64b933229f68ec805a3de38fcc

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN apk add --update --no-cache make gcc libc-dev mariadb-dev postgresql-dev sqlite-dev git
RUN gem install bundler -v 2.5.22

COPY Rakefile $HOME/
COPY Gemfile Gemfile.lock $HOME/
# Only loaded for running the specs
COPY pact_broker $HOME/pact_broker
COPY spec $HOME/spec
RUN bundle install
