version: "3.7"

services:
  stackup-base:
    image: realestate/stackup:1.9.0
    working_dir: /app
    volumes:
      - ".:/app"
    entrypoint: stackup
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  stackup-test:
    extends: stackup-base
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2

  stackup-UAT:
    extends: stackup-base
    environment:
      - AWS_DEFAULT_REGION=us-west-2

  stackup-Prod:
    extends: stackup-base
    environment:
      - AWS_DEFAULT_REGION=us-east-1
