#!/usr/bin/env bash

function docker_build_bundle_base() {
  docker build . -f Dockerfile-bundle-base -t pact_broker_bundle_base
}

function get_pact_broker_version() {
  ruby -e "puts File.read('pact_broker/Gemfile.lock').match(/pact_broker \((.*)\)/)[1]"
}
